[package]
name = "functions"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "square_function"
src = "src/bin/square_funcion.rs"

[[bin]]
name = "abs_value"
src = "src/bin/abs_value.rs"
[dependencies]
